### ISSUE TITLE
EmrEtlRunner: fix breaking get_assets spec

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1287]
This is the current output:

```
Failures:

  1) Snowplow::EmrEtlRunner::EmrJob returns the Hadoop assets
     Failure/Error: EmrJob.get_assets("s3://hadoop-assets/", "1.0.0").should == {
     ArgumentError:
       wrong number of arguments (2 for 3)
     # ./lib/snowplow-emr-etl-runner/emr_job.rb:444:in `get_assets'
     # ./spec/snowplow-emr-etl-runner/emr_job_spec.rb:31:in `block (2 levels) in <top (required)>'

Finished in 0.00503 seconds
6 examples, 1 failure

Failed examples:

rspec ./spec/snowplow-emr-etl-runner/emr_job_spec.rb:30 # Snowplow::EmrEtlRunner::EmrJob returns the Hadoop assets

```

It looks like the fact that `get_assets` now expects a Hadoop Shred version argument has broken the test.

**Comment by alexanderdean** [comment]
Thanks for spotting this Fred!
