### ISSUE TITLE
EmrEtlRunner: add missing require time_diff to emr_job.rb

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1310]

**Comment by alexanderdean** [comment]
Adding this back in causes some weird contracts issue I don't have time to look at now:

```
   Actual: :silencer
    Value guarded in: Module::mattr_reader
    With Contract: Hash => NilClass
    At: /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.1.8/lib/active_support/core_ext/module/attribute_accessors.rb:53
	from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/contracts-0.4/lib/contracts.rb:214:in `block in call_with'
	from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/contracts-0.4/lib/contracts.rb:209:in `times'
	from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/contracts-0.4/lib/contracts.rb:209:in `call_with'
	from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/contracts-0.4/lib/decorators.rb:157:in `mattr_reader'
	from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.1.8/lib/active_support/core_ext/module/attribute_accessors.rb:208:in `mattr_accessor'
	from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.1.8/lib/active_support/logger_silence.rb:7:in `block in <module:LoggerSilence>'
	from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.1.8/lib/active_support/concern.rb:120:in `class_eval'
	from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.1.8/lib/active_support/concern.rb:120:in `append_features'
	from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.1.8/lib/active_support/logger.rb:7:in `include'
	from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.1.8/lib/active_support/logger.rb:7:in `<class:Logger>'
	from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.1.8/lib/active_support/logger.rb:6:in `<module:ActiveSupport>'
	from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.1.8/lib/active_support/logger.rb:5:in `<top (required)>'
	from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.1.8/lib/active_support.rb:27:in `require'
	from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.1.8/lib/active_support.rb:27:in `<top (required)>'
	from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.1.8/lib/active_support/all.rb:1:in `require'
	from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.1.8/lib/active_support/all.rb:1:in `<top (required)>'
	from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/time_diff-0.3.0/lib/time_diff.rb:2:in `require'
	from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/time_diff-0.3.0/lib/time_diff.rb:2:in `<top (required)>'
	from /vagrant/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_job.rb:25:in `require'
	from /vagrant/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_job.rb:25:in `<top (required)>'
	from /vagrant/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner.rb:23:in `require_relative'
	from /vagrant/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner.rb:23:in `<top (required)>'
	from bin/snowplow-emr-etl-runner:19:in `require'
	from bin/snowplow-emr-etl-runner:19:in `<main>'
```

**Comment by alexanderdean** [comment]
Pushing back - @fblundun please remove from Bee Hummingbird CHANGELOG...

**Comment by fblundun** [comment]
I've edited the CHANGELOG to remove this.

**Comment by alexanderdean** [comment]
Thanks Fred - do you have enough ---------s in the header for this release...

**Comment by fblundun** [comment]
I do now...

**Comment by alexanderdean** [comment]
Duplicate of #1346
