### ISSUE TITLE
Scala Stream Collector: make 'kinesis' configuration section optional if sending to stdout

### ISSUE THREAD

**Issue by sr-ix** [snowplow/snowplow#1355]
Getting the following exception using the Scala Collector with `stdout` config options set.

Exception:

```
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'kinesis'
    at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:115)
    at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:136)
    at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:150)
    at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:155)
    at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:209)
    at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:215)
    at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:33)
    at com.snowplowanalytics.snowplow.collectors.scalastream.CollectorConfig.<init>(ScalaCollectorApp.scala:131)
    at com.snowplowanalytics.snowplow.collectors.scalastream.ScalaCollector$delayedInit$body.apply(ScalaCollectorApp.scala:70)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
    at scala.App$class.main(App.scala:71)
    at com.snowplowanalytics.snowplow.collectors.scalastream.ScalaCollector$.main(ScalaCollectorApp.scala:38)
    at com.snowplowanalytics.snowplow.collectors.scalastream.ScalaCollector.main(ScalaCollectorApp.scala)
```

Here is the config:

``` aconf
collector {
  interface = "0.0.0.0"
  port = 8080

  production = false

  p3p {
    policyref = "/w3c/p3p.xml"
    CP = "NOI DSP COR NID PSA OUR IND COM NAV STA"
  }

  cookie {
    expiration = 365 days
  }

  sink {
    enabled = "stdout"
  }
}

akka {
  loglevel = OFF # 'OFF' for no logging, 'DEBUG' for all logging.
  loggers = []
}

spray.can.server {
  remote-address-header = on

  uri-parsing-mode = relaxed
  raw-request-uri-header = on

  parsing {
    max-uri-length = 32768
  }
}
```

**Comment by alexanderdean** [comment]
Thanks @sr-ix - have assigned the ticket. As a workaround for now, just add in a dummy `kinesis` section...

**Comment by achrefss** [comment]
I have the same exception using the Scala Collector with stdout config options set.
Any Idea please?

**Comment by BenFradet** [comment]
done
