### ISSUE TITLE
Explore logging configuration

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1526]

**Comment by fblundun** [comment]
Attempts to set the log level on startup by a command line argument fail due to our argument parsing:

```
./snowplow-stream-collector-0.3.0 --config active.hocon.sample -Dorg.slf4j.simpleLogger.defaultLogLevel=error

Exception in thread "main" org.clapper.argot.ArgotUsageException: Unknown option: -Dorg.slf4j.simpleLogger.defaultLogLevel=error

snowplow-stream-collector: Version 0.3.0. Copyright (c) 2013,
com.snowplowanalytics.

Usage: snowplow-stream-collector [OPTIONS]

OPTIONS
--config filename  Configuration file.

	at org.clapper.argot.ArgotParser.usage(Argot.scala:1294)
	at org.clapper.argot.ArgotParser$$anonfun$15.apply(Argot.scala:1372)
	at org.clapper.argot.ArgotParser$$anonfun$15.apply(Argot.scala:1372)
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
	at scala.collection.AbstractMap.getOrElse(Map.scala:58)
	at org.clapper.argot.ArgotParser.parseCompressedShortOpt(Argot.scala:1371)
	at org.clapper.argot.ArgotParser.parseShortOpt(Argot.scala:1434)
	at org.clapper.argot.ArgotParser.parseArgList(Argot.scala:1479)
	at org.clapper.argot.ArgotParser.parse(Argot.scala:1132)
	at org.clapper.argot.ArgotParser.parse(Argot.scala:1118)
	at com.snowplowanalytics.snowplow.collectors.scalastream.ScalaCollector$delayedInit$body.apply(ScalaCollectorApp.scala:65)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
	at com.snowplowanalytics.snowplow.collectors.scalastream.ScalaCollector$.main(ScalaCollectorApp.scala:38)
	at com.snowplowanalytics.snowplow.collectors.scalastream.ScalaCollector.main(ScalaCollectorApp.scala)
```

**Comment by alexanderdean** [comment]
Maybe we make the log level a proper argument?

**Comment by fblundun** [comment]
I think that's a good idea - the other possibilities would be setting it in the configuration hocon or getting it from an environment variable.

**Comment by fblundun** [comment]
At the moment we make are jars executable by prepending the `defaultShellScript` [here](https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-kinesis-enrich/project/BuildSettings.scala#L50) which is

```bash
#!/usr/bin/env sh
exec java -jar "$0" "$@"
```

Should we instead copy the prepended script from the EER [here](https://github.com/snowplow/snowplow/blob/master/3-enrich/emr-etl-runner/bin/jarx-stub.sh#L24)?

```bash
#!/usr/bin/env sh
exec "$java" $java_args -jar $MYSELF "$@"
```

This would allow you to specify JVM arguments, e.g.

```bash
java_args="-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xcompile.invokedynamic=false" ./myexecutable
```

I think this would also let you pass the `-Dorg.slf4j.simpleLogger.defaultLogLevel=error` argument.

**Comment by alexanderdean** [comment]
I think that's a great idea!
