### ISSUE TITLE
Scala Common Enrich: catch exception with corrupt URI in MandrillAdapter

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1569]
```
Caused by: java.lang.IllegalArgumentException: Malformed escape pair at index 72648: http://localhost/?mandrill_events=...
    at java.net.URI.create(URI.java:859)
    at com.snowplowanalytics.snowplow.enrich.common.adapters.registry.MandrillAdapter$.payloadBodyToEvents(MandrillAdapter.scala:161)
    at com.snowplowanalytics.snowplow.enrich.common.adapters.registry.MandrillAdapter$.toRawEvents(MandrillAdapter.scala:110)
    at com.snowplowanalytics.snowplow.enrich.common.adapters.AdapterRegistry$.toRawEvents(AdapterRegistry.scala:75)
    at com.snowplowanalytics.snowplow.enrich.common.EtlPipeline$$anonfun$1$$anonfun$apply$1.apply(EtlPipeline.scala:78)
    at com.snowplowanalytics.snowplow.enrich.common.EtlPipeline$$anonfun$1$$anonfun$apply$1.apply(EtlPipeline.scala:76)
    at scala.Option.map(Option.scala:145)
    at com.snowplowanalytics.snowplow.enrich.common.EtlPipeline$$anonfun$1.apply(EtlPipeline.scala:76)
    at com.snowplowanalytics.snowplow.enrich.common.EtlPipeline$$anonfun$1.apply(EtlPipeline.scala:74)
    at scalaz.Validation$class.map(Validation.scala:114)
    at scalaz.Success.map(Validation.scala:329)
    at com.snowplowanalytics.snowplow.enrich.common.EtlPipeline$.processEvents(EtlPipeline.scala:74)
    at com.snowplowanalytics.snowplow.enrich.hadoop.EtlJob$$anonfun$7.apply(EtlJob.scala:172)
    at com.snowplowanalytics.snowplow.enrich.hadoop.EtlJob$$anonfun$7.apply(EtlJob.scala:171)
    at com.twitter.scalding.MapFunction.operate(Operations.scala:58)
    at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:99)
```

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/191
