### ISSUE TITLE
Scala Kinesis Enrich: fix error when fetching MaxMind file from s3:// URI

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1645]
```
Exception in thread "main" java.net.MalformedURLException: unknown protocol: s3
    at java.net.URL.<init>(URL.java:596)
    at java.net.URL.<init>(URL.java:486)
    at java.net.URL.<init>(URL.java:435)
    at java.net.URI.toURL(URI.java:1096)
    at com.snowplowanalytics.snowplow.enrich.kinesis.KinesisEnrichApp$$anonfun$12.apply(KinesisEnrichApp.scala:152)
    at com.snowplowanalytics.snowplow.enrich.kinesis.KinesisEnrichApp$$anonfun$12.apply(KinesisEnrichApp.scala:149)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at com.snowplowanalytics.snowplow.enrich.kinesis.KinesisEnrichApp$delayedInit$body.apply(KinesisEnrichApp.scala:149)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
    at scala.App$class.main(App.scala:71)
    at com.snowplowanalytics.snowplow.enrich.kinesis.KinesisEnrichApp$.main(KinesisEnrichApp.scala:75)
    at com.snowplowanalytics.snowplow.enrich.kinesis.KinesisEnrichApp.main(KinesisEnrichApp.scala)
```

**Comment by fblundun** [comment]
The batch pipeline has [special logic](https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-hadoop-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich.hadoop/utils/FileUtils.scala#L50-L56) for the case where the URI starts "s3", but the Kinesis pipeline just tries to treat it as a normal URL.

**Comment by alexanderdean** [comment]
Sure thing - the Kinesis pipeline will need some different logic, because unlike Hadoop, it doesn't get s3:// protocol support "for free"...

**Comment by alexanderdean** [comment]
Why is this not an issue with pipelines we have running existing Kinesis Enrich, which are downloading geoip fine?
