### ISSUE TITLE
Scala Kinesis Enrich: exception installing MaxMind file must terminate

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1711]
At the moment, the code to install the MaxMind file runs in a background process:

```scala
  for (uriFilePair <- filesToCache) {
    val targetFile = new File(uriFilePair._2)
    if (! targetFile.exists) {
      val downloadProcessBuilder = uriFilePair._1.toURL #> targetFile // using sys.process
      downloadProcessBuilder.run
    }
  }
```

If the user running this does not have write permissions on the relevant folder, then this exception occurs:

```
Exception in thread "Thread-5" java.io.FileNotFoundException: ./ip_geo (Permission denied)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at scala.sys.process.ProcessBuilderImpl$FileOutput$$anonfun$$init$$3.apply(ProcessBuilderImpl.scala:32)
	at scala.sys.process.ProcessBuilderImpl$FileOutput$$anonfun$$init$$3.apply(ProcessBuilderImpl.scala:32)
	at scala.sys.process.ProcessBuilderImpl$OStreamBuilder$$anonfun$$init$$4.apply(ProcessBuilderImpl.scala:37)
	at scala.sys.process.ProcessBuilderImpl$OStreamBuilder$$anonfun$$init$$4.apply(ProcessBuilderImpl.scala:37)
	at scala.sys.process.ProcessBuilderImpl$ThreadBuilder$$anonfun$1.apply$mcV$sp(ProcessBuilderImpl.scala:57)
	at scala.sys.process.ProcessImpl$Spawn$$anon$1.run(ProcessImpl.scala:22)
```

But the startup proceeds, and all subsequent events end up in the bad bucket because they trip this (admittedly far too coarse) exception:

```scala
    try {
      ipLookups.performLookups(ip).success
    } catch {
      case _: Throwable => "Could not extract geo-location from IP address [%s]".format(ip).fail
    }
```

**Comment by alexanderdean** [comment]
Moving to Kinesis #6.

**Comment by fblundun** [comment]
If the download process fails because the MaxMind url is bad, the result will be an empty ip_geo file. This means that if the app is restarted it will see the ip_geo file and not need to download it again. Then the empty ip_geo file will be used with every event, causing every event to fail enrichment.

So the app should check not only the existence of the file but also whether it is empty.

**Comment by alexanderdean** [comment]
Thanks for exploring this Fred!
