### ISSUE TITLE
EmrEtlRunner: recover from 500 error while checking job status

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1828]
```
RestClient::InternalServerError (500 Internal Server Error): /opt/snowplow/r66-oriental-skylark/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/rest-client-1.7.3/lib/restclient/abstract_response.rb:48:in `return!' /opt/snowplow/r66-oriental-skylark/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/rest-client-1.7.3/lib/restclient/request.rb:495:in `process_result' /opt/snowplow/r66-oriental-skylark/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/rest-client-1.7.3/lib/restclient/request.rb:421:in `block in transmit' /home/snowplow2/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/net/http.rb:746:in `start' /opt/snowplow/r66-oriental-skylark/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/rest-client-1.7.3/lib/restclient/request.rb:413:in `transmit' /opt/snowplow/r66-oriental-skylark/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/rest-client-1.7.3/lib/restclient/request.rb:176:in `execute' /opt/snowplow/r66-oriental-skylark/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/rest-client-1.7.3/lib/restclient/request.rb:41:in `execute' /opt/snowplow/r66-oriental-skylark/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/rest-client-1.7.3/lib/restclient.rb:69:in `post' /opt/snowplow/r66-oriental-skylark/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/elasticity-4.0.5/lib/elasticity/aws_request.rb:34:in `submit' /opt/snowplow/r66-oriental-skylark/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/elasticity-4.0.5/lib/elasticity/emr.rb:17:in `describe_jobflow'
```

Maybe already covered by an existing fix in this release?

**Comment by fblundun** [comment]
I don't understand why this stack trace doesn't seem to involve any of the EmrEtlRunner's functions...

Anyway, this isn't covered by the current r68 list of rescued errors yet:

https://github.com/snowplow/snowplow/blob/snowplow-cli-configuration-unification/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_job.rb#L442-L453

So I'll add it as a new recovery option.

**Comment by alexanderdean** [comment]
The stack trace is incomplete - it will continue on into the wait_for...

**Comment by fblundun** [comment]
I see!

**Comment by alexanderdean** [comment]
Here's another one @fblundun : 

```
IOError (Connection reset by peer): org/jruby/ext/openssl/SSLSocket.java:677:in `sysread_nonblock' /tmp/jruby2886024548669569113extract/jruby-stdlib-1.7.19.jar!/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/buffering.rb:174:in `read_nonblock' /tmp/jruby2886024548669569113extract/jruby-stdlib-1.7.19.jar!/META-INF/jruby.home/lib/ruby/1.9/net/protocol.rb:141:in `rbuf_fill' /tmp/jruby2886024548669569113extract/jruby-stdlib-1.7.19.jar!/META-INF/jruby.home/lib/ruby/1.9/net/protocol.rb:122:in `readuntil' /tmp/jruby2886024548669569113extract/jruby-stdlib-1.7.19.jar!/META-INF/jruby.home/lib/ruby/1.9/net/protocol.rb:132:in `readline' /tmp/jruby2886024548669569113extract/jruby-stdlib-1.7.19.jar!/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:2571:in `read_status_line' /tmp/jruby2886024548669569113extract/jruby-stdlib-1.7.19.jar!/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:2560:in `read_new' /tmp/jruby2886024548669569113extract/jruby-stdlib-1.7.19.jar!/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:1328:in `transport_request' org/jruby/RubyKernel.java:1270:in `catch' /tmp/jruby2886024548669569113extract/jruby-stdlib-1.7.19.jar!/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:1325:in `transport_request' /tmp/jruby2886024548669569113extract/jruby-stdlib-1.7.19.jar!/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:1302:in `request' /opt/snowplow-r64-palila/emr-etl-runner!/gems/rest-client-1.7.3/lib/restclient/request.rb:270:in `net_http_do_request' /opt/snowplow-r64-palila/emr-etl-runner!/gems/rest-client-1.7.3/lib/restclient/request.rb:418:in `transmit' /tmp/jruby2886024548669569113extract/jruby-stdlib-1.7.19.jar!/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:746:in `start' /opt/snowplow-r64-palila/emr-etl-runner!/gems/rest-client-1.7.3/lib/restclient/request.rb:413:in `transmit' /opt/snowplow-r64-palila/emr-etl-runner!/gems/rest-client-1.7.3/lib/restclient/request.rb:176:in `execute' /opt/snowplow-r64-palila/emr-etl-runner!/gems/rest-client-1.7.3/lib/restclient/request.rb:41:in `execute' /opt/snowplow-r64-palila/emr-etl-runner!/gems/rest-client-1.7.3/lib/restclient.rb:69:in `post' /opt/snowplow-r64-palila/emr-etl-runner!/gems/elasticity-4.0.5/lib/elasticity/aws_request.rb:34:in `submit' /opt/snowplow-r64-palila/emr-etl-runner!/gems/elasticity-4.0.5/lib/elasticity/emr.rb:17:in `describe_jobflow' /opt/snowplow-r64-palila/emr-etl-runner!/gems/elasticity-4.0.5/lib/elasticity/job_flow.rb:161:in `status' /opt/snowplow-r64-palila/emr-etl-runner!/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_job.rb:352:in `wait_for' /opt/snowplow-r64-palila/emr-etl-runner!/gems/contracts-0.7/lib/contracts/method_reference.rb:46:in `send_to' /opt/snowplow-r64-palila/emr-etl-runner!/gems/contracts-0.7/lib/contracts.rb:305:in `call_with' /opt/snowplow-r64-palila/emr-etl-runner!/gems/contracts-0.7/lib/contracts/decorators.rb:159:in `common_method_added' /opt/snowplow-r64-palila/emr-etl-runner!/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_job.rb:296:in `run' /opt/snowplow-r64-palila/emr-etl-runner!/gems/contracts-0.7/lib/contracts/method_reference.rb:46:in `send_to' /opt/snowplow-r64-palila/emr-etl-runner!/gems/contracts-0.7/lib/contracts.rb:305:in `call_with' /opt/snowplow-r64-palila/emr-etl-runner!/gems/contracts-0.7/lib/contracts/decorators.rb:159:in `common_method_added' /opt/snowplow-r64-palila/emr-etl-runner!/emr-etl-runner/lib/snowplow-emr-etl-runner/runner.rb:60:in `run' /opt/snowplow-r64-palila/emr-etl-runner!/gems/contracts-0.7/lib/contracts/method_reference.rb:46:in `send_to' /opt/snowplow-r64-palila/emr-etl-runner!/gems/contracts-0.7/lib/contracts.rb:305:in `call_with' /opt/snowplow-r64-palila/emr-etl-runner!/gems/contracts-0.7/lib/contracts/decorators.rb:159:in `common_method_added' file:/opt/snowplow-r64-palila/emr-etl-runner!/emr-etl-runner/bin/snowplow-emr-etl-runner:39:in `(root)' org/jruby/RubyKernel.java:1087:in `load' file:/opt/snowplow-r64-palila/emr-etl-runner!/META-INF/main.rb:1:in `(root)' org/jruby/RubyKernel.java:1071:in `require' file:/opt/snowplow-r64-palila/emr-etl-runner!/META-INF/main.rb:1:in `(root)' /tmp/jruby2886024548669569113extract/jruby-stdlib-1.7.19.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1:in `(root)'
```
