### ISSUE TITLE
Explore user-defined enrichments

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2054]
First attempt: https://github.com/snowplow/snowplow/commit/61ad6f9bfaea7299b21d579289782e54f59c141d#commitcomment-13187113

The current idea is to have users create a class extending `IUserEnrichment` defining a method which takes an `EnrichedEvent` and returns `Unit`, i.e. it mutates the `EnrichedEvent` in place.

They would specify in the configuration where those classes can be found, what the name of the class is, and whether each class is enabled:

``` json
[
  {
    "class": "com.acme.CustomEnrichment",
    "url": "s3://path/to/customenrichment.jar",
    "enabled": true
  }
]
```

Each enabled class would then be loaded and instantiated at runtime.

Possible extension to this: the method could be given as additional argument json4s objects containing all contexts and unstructured event JSONs, so that users don't have to deserialize the `EnrichedEvent` JSON strings.

Additionally, the method could optionally derived contexts json4s objects.

**Comment by alexanderdean** [comment]
Great first spike! Feedback:

* We don't want to encourage event mutation in place - enrichments should add to the derived contexts array. The "urge" to mutate will decrease as more and more of the fat jar moves out into JSONs anyway. Eventually we will allow a special class of enrichment which is allowed to destroy/mutate an event (e.g. the AnonIpEnrichment)
* Part of the appeal of this enrichment is that you can write it in any fatjarable JVM language and include new dependencies, so it would be nice to have test implementations in Java and Clojure which use an unusual dependency. Also there shouldn't be an assumption of json4s in the API anywhere - JsonNode should be the linguafranca
* It would be nice if the enrichment supported arguments being passed from the config to the method, rather than having to hard-code all config in the method. Perhaps the method has a second argument which is a JsonNode (remember, shouldn't be Scala-specific), and then in the JSON config you can specify the argument parameters

**Comment by fblundun** [comment]
That all sounds good... So IUserEnrichment would look like this:

```scala
trait IUserEnrichment {
  @throws[Exception]
  def configure(config: JsonNode): Unit

  @throws[Exception]
  def createDerivedContexts(event: EnrichedEvent): Array[JsonNode]
}
```

**Comment by alexanderdean** [comment]
Nice. Can we express this as a Java interface rather than Scala trait as
the lowest common denominator between Java/Clojure/Scala/Kotlin?

**Comment by fblundun** [comment]
```java
interface Lol {
  
  public void configure(JsonNode config) throws Exception;

  public ArrayList<JsonNode> createDerivedContexts(
    EnrichedEvent event,
    JsonNode unstructEvent,
    ArrayList<JsonNode> existingContexts) throws Exception;
}
```

We could also have a top-level boolean configuration parameter "requiresDerivedContexts". If set to `false` then `null` would be passed as the value of `existingContexts` to every custom enrichment object. This would avoid the cost of converting existing contexts to JsonNodes for no reason.

An alternative: don't pass the existingContexts argument at all, and let the user deal with deserialization.

The same would apply to unstructured events.

**Comment by alexanderdean** [comment]
All good suggestions! This problem should diminish over time as EnrichedEvent becomes more strongly typed and Avro-ish, but agree we would need to do something in the short term.

I think the first suggestion is fine - as the `EnrichedEvent` is steadily shorn, there will be less and less that an enrichment can do without using the `existingContexts`, so any option to ignore contexts will become less and less relevant. Similarly, I think asking the user to do deserialization isn't the right direction of travel, given that we have a deserialized version of the contexts available in Common Enrich (as we are validating them).

**Comment by fblundun** [comment]
@christoph-buente - we know you're using the JavaScript enrichment. Do you have any thoughts on our discussion here about a general JVM language enrichment?

**Comment by alexanderdean** [comment]
Note that calling Clojure from Java even with a well-defined interface is somewhat involved:

http://stackoverflow.com/questions/8614734/how-do-i-implement-a-java-interface-in-clojure

Therefore, we will explicitly exclude Clojure support from this enrichment in favour of #2056. Scala, Java and Kotlin support (http://kotlinlang.org/docs/reference/java-interop.html#calling-kotlin-code-from-java) should all still be fine.

**Comment by fblundun** [comment]
TODO: check whether users will need to recompile against Scala Common Enrich when we add new fields to the EnrichedEvent class.

**Comment by christoph-buente** [comment]
Hey @fblundun 

we actually do not use the custom javascript enrichment, as we do not have access to the raw event data.

I think your interface is really spot on, given the fact that ```JsonNode unstructEvent```is actually representing the raw event object.

It would be cool to have custom enrichments, which do not require to be compiled in the SP core. I think people can be really creative when it comes to custom enrichments.

**Comment by fblundun** [comment]
We could potentially load custom enrichments into the cluster as a bootstrap action.

**Comment by fblundun** [comment]
An example of source code for a custom enrichment:

```java
package com.acme;

import java.util.ArrayList;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import com.snowplowanalytics.snowplow.enrich.common.outputs.EnrichedEvent;
import com.snowplowanalytics.snowplow.enrich.common.enrichments.IUserEnrichment;

public class MyCustomEnrichment implements IUserEnrichment {

	public void configure(JsonNode config) throws Exception {}

	public ArrayList<JsonNode> createDerivedContexts(EnrichedEvent event, JsonNode unstructEvent, ArrayList<JsonNode> existingContexts) {
		ArrayList<JsonNode> output = new ArrayList<>();
		if (event.getV_tracker() != null) {
			JsonNodeFactory factory = JsonNodeFactory.instance;
			ObjectNode root = factory.objectNode();
			root.put("schema", "iglu:com.snowplowanalytics.snowplow/my_schema/jsonschema/1-0-0");
			ObjectNode data = factory.objectNode();
			data.put("trackerType", event.getV_tracker().split("-")[0]);
			root.put("data", data);
			output.add(root);
		}
		return output;
	}
}
```

This is compiled using the Scala Common Enrich and Jackson-Databind libraries.

**Comment by alexanderdean** [comment]
Hey @fblundun ! A couple of thoughts on this:

* Can we come up with a simple example that flexes all the functionality we're going to support?
* Can we add this into: https://github.com/snowplow/snowplow-java-example-enrichment

**Comment by fblundun** [comment]
There is a subtlety here which is worth making a note of:

I am using a URLClassLoader to load the user-implemented class called `MyCustomEnrichment` from a given file location. `MyCustomEnrichment` implements `IUserInterface`, which is found in the Scala Common Enrich source.

When I attempt to run Stream Enrich using sbt, I get this error:

```
java.lang.NoClassDefFoundError: com/snowplowanalytics/snowplow/enrich/common/enrichments/IUserEnrichment
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.snowplowanalytics.snowplow.enrich.common.enrichments.registry.CustomEnrichment$$anonfun$liftedTree1$1$2.apply(CustomEnrichment.scala:104)
	at com.snowplowanalytics.snowplow.enrich.common.enrichments.registry.CustomEnrichment$$anonfun$liftedTree1$1$2.apply(CustomEnrichment.scala:100)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at com.snowplowanalytics.snowplow.enrich.common.enrichments.registry.CustomEnrichment.liftedTree1$1(CustomEnrichment.scala:100)
	at com.snowplowanalytics.snowplow.enrich.common.enrichments.registry.CustomEnrichment.instances$lzycompute(CustomEnrichment.scala:100)
	at com.snowplowanalytics.snowplow.enrich.common.enrichments.registry.CustomEnrichment.instances(CustomEnrichment.scala:100)
	at com.snowplowanalytics.snowplow.enrich.common.enrichments.registry.CustomEnrichment.getDerivedContexts(CustomEnrichment.scala:124)
	at com.snowplowanalytics.snowplow.enrich.common.enrichments.EnrichmentManager$.enrichEvent(EnrichmentManager.scala:451)
	at com.snowplowanalytics.snowplow.enrich.common.EtlPipeline$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3.apply(EtlPipeline.scala:94)
	at com.snowplowanalytics.snowplow.enrich.common.EtlPipeline$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3.apply(EtlPipeline.scala:93)
	at scalaz.NonEmptyList$class.map(NonEmptyList.scala:23)
	at scalaz.NonEmptyListFunctions$$anon$4.map(NonEmptyList.scala:196)
	at com.snowplowanalytics.snowplow.enrich.common.EtlPipeline$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2.apply(EtlPipeline.scala:93)
	at com.snowplowanalytics.snowplow.enrich.common.EtlPipeline$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2.apply(EtlPipeline.scala:91)
	at scalaz.Validation$class.map(Validation.scala:114)
	at scalaz.Success.map(Validation.scala:347)
	at com.snowplowanalytics.snowplow.enrich.common.EtlPipeline$$anonfun$1$$anonfun$apply$1.apply(EtlPipeline.scala:91)
	at com.snowplowanalytics.snowplow.enrich.common.EtlPipeline$$anonfun$1$$anonfun$apply$1.apply(EtlPipeline.scala:89)
	at scala.Option.map(Option.scala:145)
	at com.snowplowanalytics.snowplow.enrich.common.EtlPipeline$$anonfun$1.apply(EtlPipeline.scala:89)
	at com.snowplowanalytics.snowplow.enrich.common.EtlPipeline$$anonfun$1.apply(EtlPipeline.scala:87)
	at scalaz.Validation$class.map(Validation.scala:114)
	at scalaz.Success.map(Validation.scala:347)
	at com.snowplowanalytics.snowplow.enrich.common.EtlPipeline$.processEvents(EtlPipeline.scala:87)
	at com.snowplowanalytics.snowplow.enrich.kinesis.sources.AbstractSource.enrichEvents(AbstractSource.scala:184)
	at com.snowplowanalytics.snowplow.enrich.kinesis.sources.AbstractSource$$anonfun$5.apply(AbstractSource.scala:214)
	at com.snowplowanalytics.snowplow.enrich.kinesis.sources.AbstractSource$$anonfun$5.apply(AbstractSource.scala:214)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at com.snowplowanalytics.snowplow.enrich.kinesis.sources.AbstractSource.enrichAndStoreEvents(AbstractSource.scala:214)
	at com.snowplowanalytics.snowplow.enrich.kinesis.sources.KinesisSource$RawEventProcessor.processRecordsWithRetries(KinesisSource.scala:157)
	at com.snowplowanalytics.snowplow.enrich.kinesis.sources.KinesisSource$RawEventProcessor.processRecords(KinesisSource.scala:148)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.V1ToV2RecordProcessorAdapter.processRecords(V1ToV2RecordProcessorAdapter.java:42)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.call(ProcessTask.java:169)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.snowplowanalytics.snowplow.enrich.common.enrichments.IUserEnrichment
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 58 more
```

The problem appears to be that the URLClassLoader can't find the IUserEnrichment interface. However, this only happens when using `sbt run` - if I assemble the jar and then run it directly, there is no problem.

But `sbt run` is useful for rapid development so I think it's probably worth looking into a solution to this.

**Comment by alexanderdean** [comment]
Good catch!

**Comment by fblundun** [comment]
I have put an example enrichment in the snowplow-java-example-enrichment project and added a couple of TODOs to the kinesis-custom-jar branch.

**Comment by alexanderdean** [comment]
Awesome - thanks so much @fblundun !

**Comment by alexanderdean** [comment]
I think in a Docker world the idea of having the adapter or enricher connected over the network at runtime is much nicer than modifying the build artifact.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/None

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/253
