### ISSUE TITLE
Scala Hadoop Shred: don't error for schemas with an incorrect $schema field

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2063]

**Comment by fblundun** [comment]
```
[debug] Running TaskDef(com.snowplowanalytics.snowplow.enrich.hadoop.jobs.good.LinkClickEventSpec, sbt.SubclassFingerprintWrapper@1a222f0c, false, [SuiteSelector])
java.lang.Throwable: If you know what exactly caused this error, please consider contributing to GitHub via following link.
https://github.com/twitter/scalding/wiki/Common-Exceptions-and-possible-reasons#javaneturisyntaxexception
	at com.twitter.scalding.Tool$.main(Tool.scala:137)
	at com.snowplowanalytics.snowplow.enrich.hadoop.jobs.JobSpecHelpers$.runJobInTool(JobSpecHelpers.scala:171)
	at com.snowplowanalytics.snowplow.enrich.hadoop.jobs.good.LinkClickEventSpec$$anonfun$1.apply$mcV$sp(LinkClickEventSpec.scala:96)
	at com.snowplowanalytics.snowplow.enrich.hadoop.jobs.good.LinkClickEventSpec$$anonfun$1.apply(LinkClickEventSpec.scala:93)
	at com.snowplowanalytics.snowplow.enrich.hadoop.jobs.good.LinkClickEventSpec$$anonfun$1.apply(LinkClickEventSpec.scala:93)
	at org.specs2.mutable.SideEffectingCreationPaths$$anonfun$executeBlock$1.apply$mcV$sp(FragmentsBuilder.scala:282)
	at org.specs2.mutable.SideEffectingCreationPaths$class.replay(FragmentsBuilder.scala:254)
	at org.specs2.mutable.Specification.replay(Specification.scala:12)
	at org.specs2.mutable.FragmentsBuilder$class.fragments(FragmentsBuilder.scala:22)
	at org.specs2.mutable.Specification.fragments(Specification.scala:12)
	at org.specs2.mutable.SpecificationLike$class.is(Specification.scala:14)
	at org.specs2.mutable.Specification.is(Specification.scala:12)
	at org.specs2.specification.SpecificationStructure$$anonfun$content$1.apply(BaseSpecification.scala:55)
	at org.specs2.specification.SpecificationStructure$$anonfun$content$1.apply(BaseSpecification.scala:55)
	at org.specs2.specification.SpecificationStructure$class.map(BaseSpecification.scala:43)
	at org.specs2.mutable.Specification.map(Specification.scala:12)
	at org.specs2.specification.SpecificationStructure$class.content(BaseSpecification.scala:55)
	at org.specs2.mutable.Specification.content$lzycompute(Specification.scala:12)
	at org.specs2.mutable.Specification.content(Specification.scala:12)
	at org.specs2.runner.TestInterfaceRunner.runSpecification(TestInterfaceRunner.scala:61)
	at org.specs2.runner.TestInterfaceRunner.run(TestInterfaceRunner.scala:54)
	at sbt.RunnerWrapper$1.runRunner(FrameworkWrapper.java:203)
	at sbt.RunnerWrapper$1.execute(FrameworkWrapper.java:239)
	at sbt.TestRunner.runTest$1(TestFramework.scala:84)
	at sbt.TestRunner.run(TestFramework.scala:94)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:207)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
	at sbt.TestFunction.apply(TestFramework.scala:224)
	at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:211)
	at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:217)
	at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:217)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: cascading.flow.FlowException: local step failed
	at cascading.flow.planner.FlowStepJob.blockOnJob(FlowStepJob.java:219)
	at cascading.flow.planner.FlowStepJob.start(FlowStepJob.java:149)
	at cascading.flow.planner.FlowStepJob.call(FlowStepJob.java:124)
	at cascading.flow.planner.FlowStepJob.call(FlowStepJob.java:43)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: cascading.pipe.OperatorException: [com.twitter.scalding.M...][com.twitter.scalding.RichPipe.each(RichPipe.scala:487)] operator Each failed executing operation
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:107)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:39)
	at cascading.flow.stream.SourceStage.map(SourceStage.java:102)
	at cascading.flow.stream.SourceStage.call(SourceStage.java:53)
	at cascading.flow.stream.SourceStage.call(SourceStage.java:38)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: How did I get there??
	at com.github.fge.jsonschema.core.util.URIUtils$2.apply(URIUtils.java:113)
	at com.github.fge.jsonschema.core.util.URIUtils$2.apply(URIUtils.java:87)
	at com.github.fge.jsonschema.core.util.URIUtils.normalizeURI(URIUtils.java:238)
	at com.github.fge.jsonschema.core.ref.JsonRef.fromURI(JsonRef.java:183)
	at com.github.fge.jsonschema.core.ref.JsonRef.fromString(JsonRef.java:207)
	at com.github.fge.jsonschema.core.tree.BaseSchemaTree.extractDollarSchema(BaseSchemaTree.java:273)
	at com.github.fge.jsonschema.core.tree.BaseSchemaTree.<init>(BaseSchemaTree.java:97)
	at com.github.fge.jsonschema.core.tree.CanonicalSchemaTree.<init>(CanonicalSchemaTree.java:50)
	at com.github.fge.jsonschema.core.load.Dereferencing$1.newTree(Dereferencing.java:50)
	at com.github.fge.jsonschema.core.load.Dereferencing.newTree(Dereferencing.java:91)
	at com.github.fge.jsonschema.core.load.SchemaLoader.load(SchemaLoader.java:136)
	at com.github.fge.jsonschema.main.JsonValidator.buildData(JsonValidator.java:233)
	at com.github.fge.jsonschema.main.JsonValidator.validateUnchecked(JsonValidator.java:149)
	at com.github.fge.jsonschema.main.JsonValidator.validateUnchecked(JsonValidator.java:171)
	at com.snowplowanalytics.iglu.client.validation.ValidatableJsonMethods$.validateAgainstSchema(validatableJson.scala:72)
	at com.snowplowanalytics.iglu.client.validation.ValidatableJsonMethods$$anonfun$validateAndIdentifySchema$2$$anonfun$apply$3$$anonfun$apply$4.apply(validatableJson.scala:134)
	at com.snowplowanalytics.iglu.client.validation.ValidatableJsonMethods$$anonfun$validateAndIdentifySchema$2$$anonfun$apply$3$$anonfun$apply$4.apply(validatableJson.scala:133)
	at scalaz.Validation$class.flatMap(Validation.scala:141)
	at scalaz.Success.flatMap(Validation.scala:329)
	at com.snowplowanalytics.iglu.client.validation.ValidatableJsonMethods$$anonfun$validateAndIdentifySchema$2$$anonfun$apply$3.apply(validatableJson.scala:133)
	at com.snowplowanalytics.iglu.client.validation.ValidatableJsonMethods$$anonfun$validateAndIdentifySchema$2$$anonfun$apply$3.apply(validatableJson.scala:132)
	at scalaz.Validation$class.flatMap(Validation.scala:141)
	at scalaz.Success.flatMap(Validation.scala:329)
	at com.snowplowanalytics.iglu.client.validation.ValidatableJsonMethods$$anonfun$validateAndIdentifySchema$2.apply(validatableJson.scala:132)
	at com.snowplowanalytics.iglu.client.validation.ValidatableJsonMethods$$anonfun$validateAndIdentifySchema$2.apply(validatableJson.scala:129)
	at scalaz.Validation$class.flatMap(Validation.scala:141)
	at scalaz.Success.flatMap(Validation.scala:329)
	at com.snowplowanalytics.iglu.client.validation.ValidatableJsonMethods$.validateAndIdentifySchema(validatableJson.scala:129)
	at com.snowplowanalytics.iglu.client.validation.ValidatableJsonNode.validateAndIdentifySchema(validatableJson.scala:233)
	at com.snowplowanalytics.snowplow.enrich.hadoop.shredder.Shredder$$anonfun$shred$1$$anonfun$apply$5.apply(Shredder.scala:128)
	at com.snowplowanalytics.snowplow.enrich.hadoop.shredder.Shredder$$anonfun$shred$1$$anonfun$apply$5.apply(Shredder.scala:126)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at com.snowplowanalytics.snowplow.enrich.hadoop.shredder.Shredder$$anonfun$shred$1.apply(Shredder.scala:126)
	at com.snowplowanalytics.snowplow.enrich.hadoop.shredder.Shredder$$anonfun$shred$1.apply(Shredder.scala:124)
	at scalaz.Validation$class.map(Validation.scala:114)
	at scalaz.Success.map(Validation.scala:329)
	at com.snowplowanalytics.snowplow.enrich.hadoop.shredder.Shredder$.shred(Shredder.scala:124)
	at com.snowplowanalytics.snowplow.enrich.hadoop.ShredJob$$anonfun$loadAndShred$1.apply(ShredJob.scala:74)
	at com.snowplowanalytics.snowplow.enrich.hadoop.ShredJob$$anonfun$loadAndShred$1.apply(ShredJob.scala:73)
	at scalaz.Validation$class.flatMap(Validation.scala:141)
	at scalaz.Success.flatMap(Validation.scala:329)
	at com.snowplowanalytics.snowplow.enrich.hadoop.ShredJob$.loadAndShred(ShredJob.scala:73)
	at com.snowplowanalytics.snowplow.enrich.hadoop.ShredJob$$anonfun$5.apply(ShredJob.scala:138)
	at com.snowplowanalytics.snowplow.enrich.hadoop.ShredJob$$anonfun$5.apply(ShredJob.scala:137)
	at com.twitter.scalding.MapFunction.operate(Operations.scala:58)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:99)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:39)
	at cascading.flow.stream.SourceStage.map(SourceStage.java:102)
	at cascading.flow.stream.SourceStage.call(SourceStage.java:53)
	at cascading.flow.stream.SourceStage.call(SourceStage.java:38)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.URISyntaxException: Expected scheme-specific part at index 5: iglu:
	at java.net.URI$Parser.fail(URI.java:2829)
	at java.net.URI$Parser.failExpecting(URI.java:2835)
	at java.net.URI$Parser.parse(URI.java:3038)
	at java.net.URI.<init>(URI.java:680)
	at com.github.fge.jsonschema.core.util.URIUtils$2.apply(URIUtils.java:110)
	at com.github.fge.jsonschema.core.util.URIUtils$2.apply(URIUtils.java:87)
	at com.github.fge.jsonschema.core.util.URIUtils.normalizeURI(URIUtils.java:238)
	at com.github.fge.jsonschema.core.ref.JsonRef.fromURI(JsonRef.java:183)
	at com.github.fge.jsonschema.core.ref.JsonRef.fromString(JsonRef.java:207)
	at com.github.fge.jsonschema.core.tree.BaseSchemaTree.extractDollarSchema(BaseSchemaTree.java:273)
	at com.github.fge.jsonschema.core.tree.BaseSchemaTree.<init>(BaseSchemaTree.java:97)
	at com.github.fge.jsonschema.core.tree.CanonicalSchemaTree.<init>(CanonicalSchemaTree.java:50)
	at com.github.fge.jsonschema.core.load.Dereferencing$1.newTree(Dereferencing.java:50)
	at com.github.fge.jsonschema.core.load.Dereferencing.newTree(Dereferencing.java:91)
	at com.github.fge.jsonschema.core.load.SchemaLoader.load(SchemaLoader.java:136)
	at com.github.fge.jsonschema.main.JsonValidator.buildData(JsonValidator.java:233)
	at com.github.fge.jsonschema.main.JsonValidator.validateUnchecked(JsonValidator.java:149)
	at com.github.fge.jsonschema.main.JsonValidator.validateUnchecked(JsonValidator.java:171)
	at com.snowplowanalytics.iglu.client.validation.ValidatableJsonMethods$.validateAgainstSchema(validatableJson.scala:72)
	at com.snowplowanalytics.iglu.client.validation.ValidatableJsonMethods$$anonfun$validateAndIdentifySchema$2$$anonfun$apply$3$$anonfun$apply$4.apply(validatableJson.scala:134)
	at com.snowplowanalytics.iglu.client.validation.ValidatableJsonMethods$$anonfun$validateAndIdentifySchema$2$$anonfun$apply$3$$anonfun$apply$4.apply(validatableJson.scala:133)
	at scalaz.Validation$class.flatMap(Validation.scala:141)
	at scalaz.Success.flatMap(Validation.scala:329)
	at com.snowplowanalytics.iglu.client.validation.ValidatableJsonMethods$$anonfun$validateAndIdentifySchema$2$$anonfun$apply$3.apply(validatableJson.scala:133)
	at com.snowplowanalytics.iglu.client.validation.ValidatableJsonMethods$$anonfun$validateAndIdentifySchema$2$$anonfun$apply$3.apply(validatableJson.scala:132)
	at scalaz.Validation$class.flatMap(Validation.scala:141)
	at scalaz.Success.flatMap(Validation.scala:329)
	at com.snowplowanalytics.iglu.client.validation.ValidatableJsonMethods$$anonfun$validateAndIdentifySchema$2.apply(validatableJson.scala:132)
	at com.snowplowanalytics.iglu.client.validation.ValidatableJsonMethods$$anonfun$validateAndIdentifySchema$2.apply(validatableJson.scala:129)
	at scalaz.Validation$class.flatMap(Validation.scala:141)
	at scalaz.Success.flatMap(Validation.scala:329)
	at com.snowplowanalytics.iglu.client.validation.ValidatableJsonMethods$.validateAndIdentifySchema(validatableJson.scala:129)
	at com.snowplowanalytics.iglu.client.validation.ValidatableJsonNode.validateAndIdentifySchema(validatableJson.scala:233)
	at com.snowplowanalytics.snowplow.enrich.hadoop.shredder.Shredder$$anonfun$shred$1$$anonfun$apply$5.apply(Shredder.scala:128)
	at com.snowplowanalytics.snowplow.enrich.hadoop.shredder.Shredder$$anonfun$shred$1$$anonfun$apply$5.apply(Shredder.scala:126)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at com.snowplowanalytics.snowplow.enrich.hadoop.shredder.Shredder$$anonfun$shred$1.apply(Shredder.scala:126)
	at com.snowplowanalytics.snowplow.enrich.hadoop.shredder.Shredder$$anonfun$shred$1.apply(Shredder.scala:124)
	at scalaz.Validation$class.map(Validation.scala:114)
	at scalaz.Success.map(Validation.scala:329)
	at com.snowplowanalytics.snowplow.enrich.hadoop.shredder.Shredder$.shred(Shredder.scala:124)
	at com.snowplowanalytics.snowplow.enrich.hadoop.ShredJob$$anonfun$loadAndShred$1.apply(ShredJob.scala:74)
	at com.snowplowanalytics.snowplow.enrich.hadoop.ShredJob$$anonfun$loadAndShred$1.apply(ShredJob.scala:73)
	at scalaz.Validation$class.flatMap(Validation.scala:141)
	at scalaz.Success.flatMap(Validation.scala:329)
	at com.snowplowanalytics.snowplow.enrich.hadoop.ShredJob$.loadAndShred(ShredJob.scala:73)
	at com.snowplowanalytics.snowplow.enrich.hadoop.ShredJob$$anonfun$5.apply(ShredJob.scala:138)
	at com.snowplowanalytics.snowplow.enrich.hadoop.ShredJob$$anonfun$5.apply(ShredJob.scala:137)
	at com.twitter.scalding.MapFunction.operate(Operations.scala:58)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:99)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:39)
	at cascading.flow.stream.SourceStage.map(SourceStage.java:102)
	at cascading.flow.stream.SourceStage.call(SourceStage.java:53)
	at cascading.flow.stream.SourceStage.call(SourceStage.java:38)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] Could not run test com.snowplowanalytics.snowplow.enrich.hadoop.jobs.good.LinkClickEventSpec: java.lang.Throwable: If you know what exactly caused this error, please consider contributing to GitHub via following link.

```

**Comment by fblundun** [comment]
The guilty $schema: "$schema": "iglu:com.redacted/event/redacted/jsonschema/1-0-0"

**Comment by fblundun** [comment]
http://json-schema.org/latest/json-schema-core.html#anchor23

I think the problem is that the JSON schema library can throw an exception if the $schema field is not a well-formed URI. In the above case, removing the colon from the field prevents the exception.

**Comment by fblundun** [comment]
I think Hadoop Shred should have an equivalent of https://github.com/snowplow/snowplow/issues/1954 to make this sort of thing easier to debug in future.

**Comment by fblundun** [comment]
This is the origin of the failure: https://github.com/fge/json-schema-validator/blob/fd781ef26318ce4b7bde294307dd32d6c2e8da03/src/main/java/com/github/fge/jsonschema/processors/validation/ValidationStack.java#L208.

There's room for improvement in the error message.

**Comment by fblundun** [comment]
Moving this ticket to Iglu Scala Client: https://github.com/snowplow/iglu-scala-client/issues/33
