### ISSUE TITLE
Add nicer failure message if processing or archive buckets missing

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#257]
Currently:

```
bundle exec bin/snowplow-emr-etl-runner --config ~/apps/snowplow-saas/configs/pbz-redshift/runner.yml 
Staging CloudFront logs...
Unexpected error: undefined method `files' for nil:NilClass
/home/admin/apps/snowplow/3-enrich/emr-etl-    runner/vendor/bundle/ruby/1.9.1/gems/sluice-0.0.6/lib/sluice/storage/s3.rb:85:in `is_empty?'
/home/admin/apps/snowplow/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/s3_tasks.rb:45:in `stage_logs_for_emr'
bin/snowplow-emr-etl-runner:36:in `<main>'
```

**Comment by BenFradet** [comment]
done, closing
