### ISSUE TITLE
Stream Enrich: crash when unable to find stream instead of hanging

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2584]
For some reason I can reproduce this problem by configuring a nonexistent bad stream but not be configuring a nonexistent good stream. But in the wild this bug has been seen when the consumer cannot find the good stream.

```
@400000005707948821e3aab4 [main] INFO com.snowplowanalytics.snowplow.enrich.kinesis.sinks.KinesisSink - Stream snowplow-com-avalanche-main-enriched doesn't exist or is not active
@400000005707948821e3b284 Exception in thread "main" java.lang.RuntimeException: Cannot write because stream snowplow-com-avalanche-main-enriched does not exist or is not active
@400000005707948821e3b66c       at com.snowplowanalytics.snowplow.enrich.kinesis.sinks.KinesisSink.loadStream(KinesisSink.scala:134)
@400000005707948821e3ba54       at com.snowplowanalytics.snowplow.enrich.kinesis.sinks.KinesisSink.<init>(KinesisSink.scala:93)
@400000005707948821e3f4ec       at com.snowplowanalytics.snowplow.enrich.kinesis.sources.AbstractSource$$anon$1.initialValue(AbstractSource.scala:157)
@400000005707948821e3f8d4       at com.snowplowanalytics.snowplow.enrich.kinesis.sources.AbstractSource$$anon$1.initialValue(AbstractSource.scala:155)
@400000005707948821e3f8d4       at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:160)
@400000005707948821e3fcbc       at java.lang.ThreadLocal.get(ThreadLocal.java:150)
@400000005707948821e400a4       at com.snowplowanalytics.snowplow.enrich.kinesis.sources.KinesisSource.run(KinesisSource.scala:102)
@400000005707948821e4048c       at com.snowplowanalytics.snowplow.enrich.kinesis.KinesisEnrichApp$delayedInit$body.apply(KinesisEnrichApp.scala:189)
@400000005707948821e4142c       at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
@400000005707948821e4142c       at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
@400000005707948821e41814       at scala.App$$anonfun$main$1.apply(App.scala:71)
@400000005707948821e41814       at scala.App$$anonfun$main$1.apply(App.scala:71)
@400000005707948821e41bfc       at scala.collection.immutable.List.foreach(List.scala:318)
@400000005707948821e41fe4       at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
@400000005707948821e423cc       at scala.App$class.main(App.scala:71)
@400000005707948821e423cc       at com.snowplowanalytics.snowplow.enrich.kinesis.KinesisEnrichApp$.main(KinesisEnrichApp.scala:76)
@400000005707948821e427b4       at com.snowplowanalytics.snowplow.enrich.kinesis.KinesisEnrichApp.main(KinesisEnrichApp.scala)

```

**Comment by fblundun** [comment]
I have only found one way to resolve this: using Runtime.getRuntime.halt().
