### ISSUE TITLE
Scala Stream Collector: crash instead of hanging when unable to load logger

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2588]
```
@40000000570dfd54211c99c4 + java -Xmx8g -jar /opt/snowplow/kinesis-applications/./snowplow-stream-collector-0.6.0 --config snowplow-stream-collector-0.6.0.hocon
@40000000570dfda41a4e5a24 [WARN] [04/13/2016 08:04:41.505] [main] [EventStream(akka://scala-stream-collector)] Log
ger log1-Slf4jLogger did not respond within Timeout(5000 milliseconds) to InitializeLogger(bus)
@40000000570dfda41a56d9ec 08:04:41.544 [scala-stream-collector-akka.actor.default-dispatcher-4] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
@40000000570dfda41a84e6fc error while starting up EventHandler
@40000000570dfda41a8b3444 akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log1-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIME$
@40000000570dfda41a920a44       at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:119)
@40000000570dfda41a93005c       at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:118)
@40000000570dfda41a93eabc       at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
@40000000570dfda41a94e0d4       at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185)
@40000000570dfda41a95bf7c       at scala.util.Try$.apply(Try.scala:161)
@40000000570dfda41a969e24       at scala.util.Failure.recover(Try.scala:185)
@40000000570dfda41a978884       at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:118)
@40000000570dfda41a98578c       at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:113)
@40000000570dfda41a99036c       at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:722)
@40000000570dfda41a99883c       at scala.collection.Iterator$class.foreach(Iterator.scala:727)
@40000000570dfda41a9a18c4       at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
@40000000570dfda41a9a99ac       at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
@40000000570dfda41a9b16ac       at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
@40000000570dfda41a9b9794       at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:721)
@40000000570dfda41a9c2434       at akka.event.LoggingBus$class.startDefaultLoggers(Logging.scala:113)
@40000000570dfda41a9ca134       at akka.event.EventStream.startDefaultLoggers(EventStream.scala:26)
@40000000570dfda41a9d1e34       at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:623)
@40000000570dfda41a9daad4       at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:579)
@40000000570dfda41a9e27d4       at akka.actor.ActorSystemImpl._start(ActorSystem.scala:577)
@40000000570dfda41a9ea4d4       at akka.actor.ActorSystemImpl.start(ActorSystem.scala:588)
@40000000570dfda41a9f3174       at akka.actor.ActorSystem$.apply(ActorSystem.scala:111)
@40000000570dfda41a9faa8c       at akka.actor.ActorSystem$.apply(ActorSystem.scala:104)
@40000000570dfda41aa0278c       at akka.actor.ActorSystem$.create(ActorSystem.scala:66)
@40000000570dfda41aa0bbfc       at com.snowplowanalytics.snowplow.collectors.scalastream.ScalaCollector$delayedInit$body.apply(ScalaCollectorApp.scala:75)
@40000000570dfda41aa1489c       at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
@40000000570dfda41aa1c59c       at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
@40000000570dfda41aa265c4       at scala.App$$anonfun$main$1.apply(App.scala:71)
@40000000570dfda41aa2daf4       at scala.App$$anonfun$main$1.apply(App.scala:71)
@40000000570dfda41aa35bdc       at scala.collection.immutable.List.foreach(List.scala:318)
@40000000570dfda41aa3e0ac       at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
@40000000570dfda41aa42ae4       at scala.App$class.main(App.scala:71)
@40000000570dfda41aa4e27c       at com.snowplowanalytics.snowplow.collectors.scalastream.ScalaCollector$.main(ScalaCollectorApp.scala:42)
@40000000570dfda41aa56b34       at com.snowplowanalytics.snowplow.collectors.scalastream.ScalaCollector.main(ScalaCollectorApp.scala)
@40000000570dfda41aa78a2c Caused by: akka.event.Logging$LoggerInitializationException: Logger log1-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]
@40000000570dfda41aa812e4       at akka.event.LoggingBus$class.akka$event$LoggingBus$$addLogger(Logging.scala:194)
@40000000570dfda41aa893cc       at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$4.apply(Logging.scala:117)
@40000000570dfda41aa914b4       at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$4.apply(Logging.scala:116)
@40000000570dfda41aa9fb2c       at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
@40000000570dfda41aaa7444       at scala.util.Try$.apply(Try.scala:161)
@40000000570dfda41aaaf144       at scala.util.Success.map(Try.scala:206)
@40000000570dfda41aab722c       at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:116)
@40000000570dfda41aac069c       ... 26 more
```

**Comment by fblundun** [comment]
I was able to reproduce this by setting `akka.logger-startup-timeout = 1ms`.

Bumping Akka to 2.3.9 and Spray to 1.3.3 solves this - the app crashes immediately instead of hanging. So I am closing this issue because it is covered by #2522.
