### ISSUE TITLE
collector-0.9.0 and enrich-0.10.0 won't start without kafka config even when using kinesis

### ISSUE THREAD

**Issue by asabourin** [snowplow/snowplow#2995]
Hey guys, just upgraded to r85 and even with `enabled = "kinesis"` still in my collector config I was getting 
```
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'kafka'
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
	at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:218)
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:224)
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:33)
	at com.snowplowanalytics.snowplow.collectors.scalastream.CollectorConfig.<init>(ScalaCollectorApp.scala:203)
	at com.snowplowanalytics.snowplow.collectors.scalastream.ScalaCollector$delayedInit$body.apply(ScalaCollectorApp.scala:81)
```
until I added a dummy entry for kafka
```
 kafka {
      brokers: ""

      # Data will be stored in the following topics
      topic {
        good: ""
        bad: ""
      }
    }
```

Similar story with enrich, still using kinesis and not starting until I added
 ```
kafka {
    brokers: "localhost:9092"
  }
```

**Comment by alexanderdean** [comment]
Right - yes the whole config file is expected to be present whether you are using Kinesis or Kafka, this is covered in the upgrade section:

http://snowplowanalytics.com/blog/2016/11/15/snowplow-r85-metamorphosis-released-with-beta-apache-kafka-support/#upgrading

**Comment by asabourin** [comment]
Cool yes it was an easy fix but I thought that might be confusing for people sticking with Kinesis so  good to have it documented here. Thanks for the quick reply!
