### ISSUE TITLE
Kinesis Elasticsearch Sink: Uncaught exception when first record in a buffer exceeds the buffer byte size limit

### ISSUE THREAD

**Issue by acgray** [snowplow/snowplow#3019]
The buffer splitting routing doesn't correctly handle the case where the first record exceeds the buffer byte size limit and throws an IndexOutOfBoundsException:

```
java.lang.IndexOutOfBoundsException: 1
	at com.snowplowanalytics.snowplow.storage.kinesis.elasticsearch.SnowplowElasticsearchEmitter.splitBufferRec$1(SnowplowElasticsearchEmitter.scala:187)
	at com.snowplowanalytics.snowplow.storage.kinesis.elasticsearch.SnowplowElasticsearchEmitter.splitBuffer(SnowplowElasticsearchEmitter.scala:213)
	at com.snowplowanalytics.snowplow.storage.kinesis.elasticsearch.SnowplowElasticsearchEmitter.sendToElasticsearch(SnowplowElasticsearchEmitter.scala:145)
	at com.snowplowanalytics.snowplow.storage.kinesis.elasticsearch.SnowplowElasticsearchEmitter.emit(SnowplowElasticsearchEmitter.scala:128)
	at com.snowplowanalytics.snowplow.storage.kinesis.elasticsearch.SnowplowElasticsearchEmitterSpec$$anonfun$1$$anonfun$apply$24.apply(SnowplowElasticsearchEmitterSpec.scala:118)
	at com.snowplowanalytics.snowplow.storage.kinesis.elasticsearch.SnowplowElasticsearchEmitterSpec$$anonfun$1$$anonfun$apply$24.apply(SnowplowElasticsearchEmitterSpec.scala:101)
```

(This is very difficult to see because the Amazon KCL suppresses the exception at runtime!)

**Comment by alexanderdean** [comment]
Ah wow - great sleuthing @acgray !

**Comment by acgray** [comment]
Thanks! Now I guess I should fix the bug in the KCL that stopped the exception from propagating in the first place... 🙄

**Comment by BenFradet** [comment]
migrated to snowplow/snowplow-elasticsearch-loader#11

will integrate #3020
