### ISSUE TITLE
Stream Enrich: add support for new AWS regions

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#3161]
I imagine a bump in the underlying AWS libraries will fix the issue for this region.

```
Exception in thread "main" java.lang.IllegalArgumentException: The specified region name is not valid
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisClientLibConfiguration.checkIsRegionNameValid(KinesisClientLibConfiguration.java:323)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisClientLibConfiguration.withRegionName(KinesisClientLibConfiguration.java:747)
	at com.snowplowanalytics.snowplow.enrich.kinesis.sources.KinesisSource.run(KinesisSource.scala:94)
	at com.snowplowanalytics.snowplow.enrich.kinesis.KinesisEnrichApp$delayedInit$body.apply(KinesisEnrichApp.scala:187)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
	at com.snowplowanalytics.snowplow.enrich.kinesis.KinesisEnrichApp$.main(KinesisEnrichApp.scala:71)
	at com.snowplowanalytics.snowplow.enrich.kinesis.KinesisEnrichApp.main(KinesisEnrichApp.scala)
```

**Comment by alexanderdean** [comment]
Thanks good catch

**Comment by Graham-M** [comment]
And London (eu-west-2) whilst you're there, please and thank you.

**Comment by BenFradet** [comment]
This is a byproduct of library upgrades, notably #3377, closing
