### ISSUE TITLE
EMRETL 'main' throwing Spark Exception

### ISSUE THREAD

**Issue by joshuacox** [snowplow/snowplow#3395]
I've got an issue that doesn't match the [troubleshooting guide](https://github.com/snowplow/snowplow/wiki/Troubleshooting-jobs-on-Elastic-MapReduce)  as far as I can tell. One of the job steps fails with this at the error output:

```
17/08/18 19:04:04 INFO Client: Application report for application_15 (state: RUNNING)
17/08/18 19:04:05 INFO Client: Application report for application_15 (state: FINISHED)
17/08/18 19:04:05 INFO Client: 
	 client token: N/A
	 diagnostics: N/A
	 ApplicationMaster host: 192.168.14.14
	 ApplicationMaster RPC port: 0
	 queue: default
	 start time: 15
	 final status: FAILED
	 tracking URL: http://ip-west-1.compute.internal:20888/proxy/application_15blah
	 user: hadoop
Exception in thread "main" org.apache.spark.SparkException: Application application_15blah finished with failed status
	at org.apache.spark.deploy.yarn.Client.run(Client.scala:1167)
	at org.apache.spark.deploy.yarn.Client$.main(Client.scala:1213)
	at org.apache.spark.deploy.yarn.Client.main(Client.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
17/08/18 19:04:05 INFO ShutdownHookManager: Shutdown hook called
17/08/18 19:04:05 INFO ShutdownHookManager: Deleting directory /mnt/tmp/spark-bablah
Command exiting with ret '1'
```

additional info: it's a clouddfront collector saving into s3  buckets setup before the lascaux release, but I think I've got all the permission up to date and correct, and emretl is being ran in a [container](https://github.com/webhostingcoopteam/snowplow-emretlrunner)  on my local laptop

**Comment by BenFradet** [comment]
You'll have to look into the EMR logs, and please direct any support questions to our forums: https://discourse.snowplowanalytics.com/

**Comment by joshuacox** [comment]
anyone stumbling in here from searching similar terms should go [here](https://discourse.snowplowanalytics.com/t/emretl-main-throwing-spark-exception/1407)
