### ISSUE TITLE
error installing python tracker with pip

### ISSUE THREAD

**Issue by abioneperhobby** [snowplow/snowplow#3417]
Windows 10 64 bit updated.

```
C:\Users\andrea.bisello>pip3 -V
pip 9.0.1 from c:\python36\lib\site-packages (python 3.6)
```

```
C:\Users\andrea.bisello>pip3 install snowplow-tracker --no-cache-dir
Collecting snowplow-tracker
  Downloading snowplow-tracker-0.8.0.tar.gz
Requirement already satisfied: greenlet==0.4.10 in c:\python36\lib\site-packages (from snowplow-tracker)
Requirement already satisfied: requests==2.2.1 in c:\python36\lib\site-packages (from snowplow-tracker)
Requirement already satisfied: pycontracts==1.7.6 in c:\python36\lib\site-packages (from snowplow-tracker)
Requirement already satisfied: celery==3.1.11 in c:\python36\lib\site-packages (from snowplow-tracker)
Collecting gevent==1.0.2 (from snowplow-tracker)
  Downloading gevent-1.0.2.tar.gz (1.7MB)
    100% |████████████████████████████████| 1.7MB 473kB/s
Collecting redis==2.9.1 (from snowplow-tracker)
  Downloading redis-2.9.1.tar.gz (62kB)
    100% |████████████████████████████████| 71kB 521kB/s
Requirement already satisfied: six==1.9.0 in c:\python36\lib\site-packages (from snowplow-tracker)
Requirement already satisfied: pyparsing in c:\python36\lib\site-packages (from pycontracts==1.7.6->snowplow-tracker)
Requirement already satisfied: decorator in c:\python36\lib\site-packages (from pycontracts==1.7.6->snowplow-tracker)
Requirement already satisfied: pytz>dev in c:\python36\lib\site-packages (from celery==3.1.11->snowplow-tracker)
Requirement already satisfied: billiard<3.4,>=3.3.0.17 in c:\python36\lib\site-packages (from celery==3.1.11->snowplow-tracker)
Requirement already satisfied: kombu<4.0,>=3.0.15 in c:\python36\lib\site-packages (from celery==3.1.11->snowplow-tracker)
Requirement already satisfied: amqp<2.0,>=1.4.9 in c:\python36\lib\site-packages (from kombu<4.0,>=3.0.15->celery==3.1.11->snowplow-tracker)
Requirement already satisfied: anyjson>=0.3.3 in c:\python36\lib\site-packages (from kombu<4.0,>=3.0.15->celery==3.1.11->snowplow-tracker)
Installing collected packages: gevent, redis, snowplow-tracker
  Running setup.py install for gevent ... error
Exception:
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 127: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\python36\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\python36\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\python36\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 127: invalid start byte

```

**Comment by BenFradet** [comment]
Hey @abioneperhobby , did you manage to get to the bottom of this?

If not, feel free to open a thread on [our Discourse](https://discourse.snowplowanalytics.com/).
