### ISSUE TITLE
Error while running collector

### ISSUE THREAD

**Issue by SarathyIyer** [snowplow/snowplow#3473]
Downloaded the latest build of collector from the master branch

Ran sbt assembly. Created the jar file. Tried to run the jar

java -jar /home/ec2-user/snowplow-stream-collector-0.10.0.jar --config /home/ec2-user/collector-dev.conf &

Here is the error and attaching the copy of collector-dev.conf

[ec2-user@ip-172-26-32-40 ~]$ Exception in thread "main" java.lang.UnsupportedCl                                                            assVersionError: com/typesafe/config/Config : Unsupported major.minor version 52                                                            .0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:14                                                            2)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2625)
        at java.lang.Class.getMethod0(Class.java:2866)
        at java.lang.Class.getMethod(Class.java:1676)
        at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
[collector-dev.txt](https://github.com/snowplow/snowplow/files/1400177/collector-dev.txt)

**Comment by chuwy** [comment]
Hi @SarathyIyer, that's a wrong JDK version. Please direct support questions to [our forums](http://discourse.snowplowanalytics.com/). Closing this.
