### ISSUE TITLE
EmrEtlRunner: tolerate more exception types in EmrJob's wait_for

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#358]
We need to handle this:

```
Unexpected error: Connection reset by peer
/home/snowplow/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/openssl/buffering.rb:174:in `sysread_nonblock'
/home/snowplow/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/openssl/buffering.rb:174:in `read_nonblock'
/home/snowplow/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/protocol.rb:141:in `rbuf_fill'
/home/snowplow/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/protocol.rb:122:in `readuntil'
/home/snowplow/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/protocol.rb:132:in `readline'
/home/snowplow/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:2563:in `read_status_line'
/home/snowplow/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:2552:in `read_new'
/home/snowplow/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:1320:in `block in transport_request'
/home/snowplow/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:1317:in `catch'
/home/snowplow/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:1317:in `transport_request'
/home/snowplow/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:1294:in `request'
/opt/snowplow/forks/sag/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
/opt/snowplow/forks/sag/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:176:in `block in transmit'
/home/snowplow/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:746:in `start'
/opt/snowplow/forks/sag/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
/opt/snowplow/forks/sag/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
/opt/snowplow/forks/sag/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
/opt/snowplow/forks/sag/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/rest-client-1.6.7/lib/restclient.rb:72:in `post'
/opt/snowplow/forks/sag/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/elasticity-2.6/lib/elasticity/aws_request.rb:27:in `submit'
/opt/snowplow/forks/sag/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/elasticity-2.6/lib/elasticity/emr.rb:17:in `describe_jobflow'
/opt/snowplow/forks/sag/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/elasticity-2.6/lib/elasticity/job_flow.rb:140:in `status'
/opt/snowplow/forks/sag/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_jobs.rb:161:in `wait_for'
/opt/snowplow/forks/sag/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_jobs.rb:138:in `run'
/opt/snowplow/forks/sag/3-enrich/emr-etl-runner/bin/snowplow-emr-etl-runner:41:in `<main>'
```

**Comment by alexanderdean** [comment]
This is happening _a lot_ at the moment - bringing forwards...

**Comment by alexanderdean** [comment]
Pushing back...

**Comment by alexanderdean** [comment]
This should be as simple as catching  `IOError (Connection reset by peer)` as well as the existing `SocketError`

**Comment by alexanderdean** [comment]
Here's another one: `Errno::ECONNREFUSED (Connection refused - Connection refused)`
