### ISSUE TITLE
Add re-attempt code for StorageLoader Redshift load

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#386]
Very occasionally the load will fail like this:

```
ERROR OUTPUT:
Unexpected error: could not connect to server: Connection timed out
        Is the server running on host "xxx.eu-west-1.redshift.amazonaws.com" (54.216.35.56) and accepting
        TCP/IP connections on port xxxx?
/opt/snowplow/master/4-storage/storage-loader/vendor/bundle/ruby/1.9.1/gems/pg-0.14.1/lib/pg.rb:38:in `initialize'
/opt/snowplow/master/4-storage/storage-loader/vendor/bundle/ruby/1.9.1/gems/pg-0.14.1/lib/pg.rb:38:in `new'
/opt/snowplow/master/4-storage/storage-loader/vendor/bundle/ruby/1.9.1/gems/pg-0.14.1/lib/pg.rb:38:in `connect'
/opt/snowplow/master/4-storage/storage-loader/lib/snowplow-storage-loader/postgres_loader.rb:90:in `execute_queries'
/opt/snowplow/master/4-storage/storage-loader/lib/snowplow-storage-loader/redshift_loader.rb:39:in `load_events'
/opt/snowplow/master/4-storage/storage-loader/bin/snowplow-storage-loader:48:in `block in <main>'
/opt/snowplow/master/4-storage/storage-loader/bin/snowplow-storage-loader:45:in `each'
/opt/snowplow/master/4-storage/storage-loader/bin/snowplow-storage-loader:45:in `<main>'
```

If this happens, let's back off and try again after 5 mins, then after 10 mins.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/snowplow-rdb-loader/issues/8
