### ISSUE TITLE
Add snowplow-spark-enrich-1.16.0.jar to snowplow-hosted-assets-ap-southeast-2 hosted assets

### ISSUE THREAD

**Issue by kingo55** [snowplow/snowplow#3882]
**Project**: Spark Enrich

**Version**: 1.16.0

**Expected behavior**: Jar exists in "snowplow-hosted-assets-ap-southeast-2"

**Actual behavior**: Jar is missing from "snowplow-hosted-assets-ap-southeast-2"

```
18/08/27 01:38:44 INFO Client: Deleted staging directory hdfs://ip-172-31-27-205.ap-southeast-2.compute.internal:8020/user/hadoop/.sparkStaging/application_1535333581168_0002
Exception in thread "main" java.io.FileNotFoundException: No such file or directory 's3://snowplow-hosted-assets-ap-southeast-2/3-enrich/spark-enrich/snowplow-spark-enrich-1.16.0.jar'
	at com.amazon.ws.emr.hadoop.fs.s3n.S3NativeFileSystem.getFileStatus(S3NativeFileSystem.java:816)
	at com.amazon.ws.emr.hadoop.fs.EmrFileSystem.getFileStatus(EmrFileSystem.java:509)
	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:337)
	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:289)
	at org.apache.spark.deploy.yarn.Client.copyFileToRemote(Client.scala:339)
	at org.apache.spark.deploy.yarn.Client.org$apache$spark$deploy$yarn$Client$$distribute$1(Client.scala:458)
	at org.apache.spark.deploy.yarn.Client$$anonfun$prepareLocalResources$10.apply(Client.scala:557)
	at org.apache.spark.deploy.yarn.Client$$anonfun$prepareLocalResources$10.apply(Client.scala:556)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.deploy.yarn.Client.prepareLocalResources(Client.scala:556)
	at org.apache.spark.deploy.yarn.Client.createContainerLaunchContext(Client.scala:814)
	at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:169)
	at org.apache.spark.deploy.yarn.Client.run(Client.scala:1091)
	at org.apache.spark.deploy.yarn.Client$.main(Client.scala:1150)
	at org.apache.spark.deploy.yarn.Client.main(Client.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```

**Steps to reproduce**: 

1. Run Enrichment with Spark Enrich 1.16.0
2. Enrichment throws an error saying the Jar doesn't exist
3. Check S3, the Jar is missing:

https://s3.console.aws.amazon.com/s3/buckets/snowplow-hosted-assets-ap-southeast-2/3-enrich/spark-enrich/?region=ap-southeast-2&tab=overview

<img width="1061" alt="screen shot 2018-08-27 at 11 56 53 am" src="https://user-images.githubusercontent.com/2361388/44636666-6960d900-a9f0-11e8-9f82-764155c83857.png">

**Comment by BenFradet** [comment]
Thanks @kingo55 , it seems I missed a tag.

It's now been published :+1:
