### ISSUE TITLE
Scala Stream Collector: graceful shutdown

### ISSUE THREAD

**Issue by cpwc** [snowplow/snowplow#3960]
**Project**: 
Scala Stream Collector

**Version**: 0.14.0

**Expected behavior**: Running `scala stream collector` within Kubernetes environment when an instance/container is being signalled to terminate. It should stop accepting requests and clear off existing tasks into the sink ASAP before fully terminating.

**Actual behavior**: Terminate with an error 

```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@51d2451 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@4e8777ab[Shutting down, pool size = 8, active threads = 1, queued tasks = 2, completed tasks = 5]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$1.execute(ExecutionContextImpl.scala:136)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:44)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:252)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:157)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Steps to reproduce**:  

 1. Have 2 or more `scala stream collector` running in Kubernetes environment.
 2. Concurrently collect data and scale down the number of replicas to 1 and watch the logs for those terminating pods.

**Comment by BenFradet** [comment]
Should be doable through a shutdown hook

**Comment by BenFradet** [comment]
btw, which platforms are you running on? I'm asking because Kinesis has something like this in place: https://github.com/snowplow/snowplow/blob/aaed36e24b3facd6048d5a71b3b44be27062fa2c/2-collectors/scala-stream-collector/kinesis/src/main/scala/com.snowplowanalytics.snowplow.collectors.scalastream/sinks/KinesisSink.scala#L64-L70

**Comment by cpwc** [comment]
@BenFradet I'm running on Kinesis. However, I'm still hitting that exception.

**Comment by dilyand** [comment]
Also possible using Akka: https://doc.akka.io/docs/akka-http/current/server-side/graceful-termination.html

**Comment by dilyand** [comment]
More context on the issue and solution(s): https://www.chrismoos.com/2016/09/28/zero-downtime-deployments-kubernetes/
