### ISSUE TITLE
scala stream collector not compiling sbt 

### ISSUE THREAD

**Issue by sushantbprise** [snowplow/snowplow#4079]
Project: Scala Stream Collector
Version: Master branch
On executing sbt test, sbt compile from terminal and even in intellij built in sbt , I get same error
 >sbt test
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
java.lang.NoClassDefFoundError: scalacache/Cache
        at sbt.xMain.run(Main.scala:72)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:56)
        at xsbt.boot.Boot$.main(Boot.scala:18)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: scalacache.Cache
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 10 more
Error during sbt execution: java.lang.NoClassDefFoundError: scalacache/Cache

Please help me with directions/solution? I am able to compile and run elastic loader thought with same intellij and same sbt configuration.

**Comment by BenFradet** [comment]
I'll try reproducing but scalacache is not on the classpath so this seems weird

**Comment by BenFradet** [comment]
I couldn't reproduce on a fresh machine with:

```bash
$ git clone https://github.com/snowplow/snowplow.git
$ cd snowplow/2-collectors/scala-stream-collector/
$ sbt test
```

can you detail how you reached this situation?

**Comment by sushantbprise** [comment]
I upgraded sbt version from 0.13.5 to 1.2.x, it worked. Thank you.
