### ISSUE TITLE
Bean Enrich: fix uncaught exception when specifying a wrong bucket for MaxMind database

### ISSUE THREAD

**Issue by benjben** [snowplow/snowplow#4271]
The job starts but keeps throwing the uncaught exception and doesn't process data.
Either the job should fail or enrichment failure bad rows should be emitted.

Stacktrace:
```
exception: "com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.io.FileNotFoundException: File spec gs://sp-max-mind-geolite2-bad/GeoLite2-City.mmdb not found
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
	at com.google.common.cache.LocalCache.getAll(LocalCache.java:4035)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getAll(LocalCache.java:4974)
	at com.spotify.scio.util.RemoteFileUtil.download(RemoteFileUtil.java:108)
	at com.spotify.scio.values.FileDistCache.prepareFiles(DistCache.scala:50)
	at com.spotify.scio.values.DistCacheMulti.init(DistCache.scala:97)
	at com.spotify.scio.values.FileDistCache.data$lzycompute(DistCache.scala:44)
	at com.spotify.scio.values.FileDistCache.data(DistCache.scala:44)
	at com.spotify.scio.values.FileDistCache.apply(DistCache.scala:40)
	at com.snowplowanalytics.snowplow.enrich.beam.Enrich$.$anonfun$enrichEvents$1(Enrich.scala:183)
	at com.spotify.scio.util.Functions$$anon$6.processElement(Functions.scala:220)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: File spec gs://sp-max-mind-geolite2-bad/GeoLite2-City.mmdb not found
	at com.spotify.scio.util.RemoteFileUtil.downloadImpl(RemoteFileUtil.java:191)
	at com.spotify.scio.util.RemoteFileUtil.access$000(RemoteFileUtil.java:52)
	at com.spotify.scio.util.RemoteFileUtil$1.load(RemoteFileUtil.java:66)
	at com.spotify.scio.util.RemoteFileUtil$1.load(RemoteFileUtil.java:63)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
	at com.google.common.cache.LocalCache.getAll(LocalCache.java:4035)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getAll(LocalCache.java:4974)
	at com.spotify.scio.util.RemoteFileUtil.download(RemoteFileUtil.java:108)
	at com.spotify.scio.values.FileDistCache.prepareFiles(DistCache.scala:50)
	at com.spotify.scio.values.DistCacheMulti.init(DistCache.scala:97)
	at com.spotify.scio.values.FileDistCache.data$lzycompute(DistCache.scala:44)
	at com.spotify.scio.values.FileDistCache.data(DistCache.scala:44)
	at com.spotify.scio.values.FileDistCache.apply(DistCache.scala:40)
	at com.snowplowanalytics.snowplow.enrich.beam.Enrich$.$anonfun$enrichEvents$1(Enrich.scala:183)
	at com.spotify.scio.util.Functions$$anon$6.processElement(Functions.scala:220)
	at com.spotify.scio.util.Functions$$anon$6$DoFnInvoker.invokeProcessElement(Unknown Source)
	at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:275)
	at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:240)
	at org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:325)
	at org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44)
	at org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49)
	at org.apache.beam.runners.dataflow.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:272)
	at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:309)
	at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.access$700(SimpleDoFnRunner.java:77)
	at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:621)
	at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:609)
	at com.spotify.scio.util.Functions$$anon$6.processElement(Functions.scala:220)
	at com.spotify.scio.util.Functions$$anon$6$DoFnInvoker.invokeProcessElement(Unknown Source)
	at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:275)
	at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:240)
	at org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:325)
	at org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44)
	at org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49)
	at org.apache.beam.runners.dataflow.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:272)
	at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:309)
	at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.access$700(SimpleDoFnRunner.java:77)
	at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:621)
	at org.apache.beam.sdk.transforms.DoFnOutputReceivers$WindowedContextOutputReceiver.output(DoFnOutputReceivers.java:71)
	at org.apache.beam.sdk.transforms.MapElements$1.processElement(MapElements.java:134)
	at org.apache.beam.sdk.transforms.MapElements$1$DoFnInvoker.invokeProcessElement(Unknown Source)
	at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:275)
	at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:240)
	at org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:325)
	at org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44)
	at org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49)
	at org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:201)
	at org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:159)
	at org.apache.beam.runners.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:77)
	at org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker.process(StreamingDataflowWorker.java:1269)
	at org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker.access$1000(StreamingDataflowWorker.java:146)
	at org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker$6.run(StreamingDataflowWorker.java:1008)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: File spec gs://sp-max-mind-geolite2-bad/GeoLite2-City.mmdb not found
	at org.apache.beam.sdk.io.FileSystems.matchSingleFileSpec(FileSystems.java:186)
	at com.spotify.scio.util.RemoteFileUtil.getMetadata(RemoteFileUtil.java:249)
	at com.spotify.scio.util.RemoteFileUtil.downloadImpl(RemoteFileUtil.java:169)
	... 57 more
"   
```

**Comment by peel** [comment]
Moved: https://github.com/snowplow/beam-enrich/issues/19
