### ISSUE TITLE
Scala Common Enrich: update parseQuerystring() to return a List[NVP]

### ISSUE THREAD

**Issue by benjben** [snowplow/snowplow#4305]
As reported on [Discourse](https://discourse.snowplowanalytics.com/t/beam-enrich-dataflow-worker-logs-reporting-java-lang-nullpointerexception/3644), a `NullPointerException` can be thrown when creating the JSON string of a `SchemaViolations` or `EnrichmentFailures` bad row (with `.compact`):

```
java.lang.NullPointerException
	at io.circe.Printer$PrintingFolder.onString(Printer.scala:278)
	at io.circe.Printer$PrintingFolder.onString(Printer.scala:262)
	at io.circe.Json$JString.foldWith(Json.scala:302)
	at io.circe.JsonObject$MapAndVectorJsonObject.appendToFolder(JsonObject.scala:433)
	at io.circe.Printer$PrintingFolder.onObject(Printer.scala:337)
	at io.circe.Printer$PrintingFolder.onObject(Printer.scala:262)
	at io.circe.Json$JObject.foldWith(Json.scala:364)
	at io.circe.JsonObject$LinkedHashMapJsonObject.appendToFolder(JsonObject.scala:326)
	at io.circe.Printer$PrintingFolder.onObject(Printer.scala:337)
	at io.circe.Printer$PrintingFolder.onObject(Printer.scala:262)
	at io.circe.Json$JObject.foldWith(Json.scala:364)
	at io.circe.JsonObject$LinkedHashMapJsonObject.appendToFolder(JsonObject.scala:326)
	at io.circe.Printer$PrintingFolder.onObject(Printer.scala:337)
	at io.circe.Printer$PrintingFolder.onObject(Printer.scala:262)
	at io.circe.Json$JObject.foldWith(Json.scala:364)
	at io.circe.JsonObject$LinkedHashMapJsonObject.appendToFolder(JsonObject.scala:326)
	at io.circe.Printer$PrintingFolder.onObject(Printer.scala:337)
	at io.circe.Printer$PrintingFolder.onObject(Printer.scala:262)
	at io.circe.Json$JObject.foldWith(Json.scala:364)
	at io.circe.JsonObject$LinkedHashMapJsonObject.appendToFolder(JsonObject.scala:326)
	at io.circe.Printer$PrintingFolder.onObject(Printer.scala:337)
	at io.circe.Printer$PrintingFolder.onObject(Printer.scala:262)
	at io.circe.Json$JObject.foldWith(Json.scala:364)
	at io.circe.Printer.pretty(Printer.scala:194)
	at io.circe.Json.noSpaces(Json.scala:116)
	at com.snowplowanalytics.snowplow.badrows.BadRow.compact(BadRow.scala:32)
	at com.snowplowanalytics.snowplow.badrows.BadRow.compact$(BadRow.scala:32)
	at com.snowplowanalytics.snowplow.badrows.BadRow$EnrichmentFailures.compact(BadRow.scala:140)
```

In the `EnrichmentFailures` and `SchemaViolations` bad rows we put the `RawEvent` with the [query string](https://github.com/snowplow-incubator/snowplow-badrows/blob/master/src/main/scala/com.snowplowanalytics.snowplow.badrows/Payload.scala#L99). If one of the value is `null`, `circe` can't create the JSON and we have the NPE.

**Comment by benjben** [comment]
The bug is confirmed:
```
scala> URLEncodedUtils.parse(URI.create("http://localhost/?a=&b=c&e"), UTF_8).asScala.toList.map(p => p.getName -> p.getValue).toMap
res1: scala.collection.immutable.Map[String,String] = Map(a -> "", b -> c, e -> null)
```

If one the query string parameter misses `=`, this parameters is treated as a key with a `null` value.

`parseQuerystring()` should be updated to return a `Map[String, Option[String]]`.

**Comment by benjben** [comment]
NVP definition can be found [here](https://github.com/snowplow-incubator/snowplow-badrows/blob/release/0.1.0/src/main/scala/com.snowplowanalytics.snowplow.badrows/Payload.scala#L264)

It's already used for `CollectorPayload` [here](https://github.com/snowplow/snowplow/blob/r118-morgantina/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/loaders/CollectorPayload.scala#L46).

**Comment by benjben** [comment]
Handled by #4292
