### ISSUE TITLE
Beam enricher can't assign Javascript Enricher

### ISSUE THREAD

**Issue by jiristepan** [snowplow/snowplow#4349]
**Project**: Beam Enricher

**Version**: 1.1.0

**Expected behavior**:
Custom javascript enricher is added. Testing on dummy enricher 

**Actual behavior**:
Folowind exception

```
[main] INFO org.apache.beam.runners.dataflow.util.PackageUtil - Uploading 250 files from PipelineOptions.filesToStage to staging location to prepare for execution.
[main] INFO org.apache.beam.runners.dataflow.util.PackageUtil - Staging files complete: 250 files cached, 0 files newly uploaded in 4 seconds
[main] INFO org.apache.beam.runners.dataflow.DataflowPipelineTranslator - Adding raw-from-pubsub/PubsubUnboundedSource as step s1
[main] INFO org.apache.beam.runners.dataflow.DataflowPipelineTranslator - Adding raw-from-pubsub/MapElements/Map as step s2
Exception in thread "main" java.lang.ClassCastException: cannot assign instance of java.lang.invoke.SerializedLambda to field com.spotify.scio.util.Functions$$anon$7.g of type scala.Function1 in instance of com.spotify.scio.util.Functions$$anon$7
        at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2301)
        at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1431)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2350)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2268)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2126)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1625)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2344)
```

**Steps to reproduce**:
Prepare new enricher in ./enrichments directory
```
{
    "schema": "iglu:com.snowplowanalytics.snowplow/javascript_script_config/jsonschema/1-0-0",
    "data": {
        "vendor": "com.snowplowanalytics.snowplow",
        "name": "javascript_script_config",
        "enabled": true,
        "parameters": {
            "script": "ZnVuY3Rpb24gcHJvY2VzcyhldmVudCkgew0KICAgIC8vdG0NCiAgICByZXR1cm4gWyANCiAgICAgICAgeyANCiAgICAgICAgICAgIHNjaGVtYTogImlnbHU6Y3ouYWN0aXZhdGUvY2wyLXN1Ym1pdC10cmlnZ2VyL2pzb25zY2hlbWEvMS0wLTAiLA0KICAgICAgICAgICAgZGF0YTogeyANCiAgICAgICAgICAgICAgICBmb3JtRmluaXNoOiAibm8iIA0KICAgICAgICAgICAgfSANCiAgICAgICAgfSANCiAgICBdOw0KfQ=="
        }
    }
}
```
The base64 string represents following function
```
function process(event) {
    return [ 
        { 
            schema: "iglu:cz.activate/cl2-submit-trigger/jsonschema/1-0-0",
            data: { 
                formFinish: "no" 
            } 
        } 
    ];
}
```

running beam-enrich with parameter --enrichments="./enrichments"  fails.

**Comment by chuwy** [comment]
Thanks @jiristepan! It indeed looks like a bug - we never had a unit test for JS Enrichment in Beam Enrich.

Also, we recently extracted Beam Enrich into its own repo and planning to use the monorepo a lot less, so I'm moving the ticket into appropriate bugtracker:https://github.com/snowplow/beam-enrich/issues/42
