### ISSUE TITLE
Scala Stream Collector: Pubsub - java.lang.IllegalArgumentException. When building BatchingSettings, values `recordLimit` and `byteLimit` not read as Long.

### ISSUE THREAD

**Issue by kaaquist** [snowplow/snowplow#4377]
**Scala Stream Collector - Pubsub**: 

**Version**: 1.0.1 - Master Branch

**Expected behavior**:
Load batching settings from bufferConfig 

**Actual behavior**:
Try to load from bufferConfig, but gets an `java.lang.IllegalArgumentException`. When building BatchingSettings, because values for `recordLimit` and `byteLimit` gets loaded as a none Long from bufferConfig. 

**Steps to reproduce**:
Just build and run the pubsub collector with example config, where basic settings has been created.
Here is an instruction: [link](https://discourse.snowplowanalytics.com/t/pubsub-collector-1-0-1-buffer-timelimit-problems/4180)

**Exception**
```
Exception in thread "main" java.lang.IllegalArgumentException: elementCountThreshold must be either unset or positive
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at com.google.api.gax.batching.BatchingSettings$Builder.build(BatchingSettings.java:167)
	at com.snowplowanalytics.snowplow.collectors.scalastream.sinks.GooglePubSubSink$.batchingSettings(GooglePubSubSink.scala:78)
	at com.snowplowanalytics.snowplow.collectors.scalastream.sinks.GooglePubSubSink$.createAndInitialize(GooglePubSubSink.scala:41)
	at com.snowplowanalytics.snowplow.collectors.scalastream.GooglePubSubCollector$.$anonfun$main$2(GooglePubSubCollector.scala:35)
	at scala.util.Either.flatMap(Either.scala:341)
	at com.snowplowanalytics.snowplow.collectors.scalastream.GooglePubSubCollector$.main(GooglePubSubCollector.scala:28)
	at com.snowplowanalytics.snowplow.collectors.scalastream.GooglePubSubCollector.main(GooglePubSubCollector.scala)
```

**Comment by kaaquist** [comment]
I have created a PR and added to the necessary for me to move forward. Hope that others will find it useful too.

**Comment by kaaquist** [comment]
Ok, it seems that I got this here wrong. Sorry!
`recordLimit` value needed to be positive number, and I had choosen `0` (zero) which is not supported.
I will close the issue.
